---
name: sync-ec-tasks

on:
  workflow_dispatch:
  schedule:
    # At 09:00 UTC on Tuesday
    - cron: '0 9 * * 1-5'

permissions:
  contents: read

jobs:
  sync-ec-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout tekton-catalog
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: conforma/tekton-catalog
        ref: main
        path: tekton-catalog

    - name: Checkout ec
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: conforma/cli
        ref: main
        path: cli

    - name: Sync tasks
      run: ./hack/sync-ec-cli-tasks.sh ../cli
      working-directory: tekton-catalog
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
