---
name: sync-ec-cli-tasks

on:
  workflow_dispatch:
  schedule:
    # At 09:00 UTC on Tuesday
    - cron: '0 9 * * 1-5'

permissions:
  contents: read

jobs:
  sync-ec-cli-tasks:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit
        disable-telemetry: true

    - name: Checkout tekton-catalog
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: enterprise-contract/tekton-catalog
        ref: main
        path: tekton-catalog

    - name: Checkout ec-cli
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      with:
        repository: enterprise-contract/ec-cli
        ref: main
        path: ec-cli

    - name: Sync tasks
      run: ./hack/sync-ec-cli-tasks.sh ../ec-cli
      working-directory: tekton-catalog
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
